WebTest/Web2/Pages/Database/Analyzes/Analyzes.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Web2.Pages.Database.Analyzes
{
    public class AnalyzesModel : PageModel
    {
        [BindProperty]
        public Models.Analyzes Analyzes { get; set; }
        public List<SelectListItem>? GetGroup()
        {
            List<SelectListItem> group = new List<SelectListItem>();
            group.Add(new SelectListItem() { Text = "Контрольная группа", Value = "1" });
            group.Add(new SelectListItem() { Text = "Основная группа", Value = "2" });
            group.Add(new SelectListItem() { Text = "Группа сравнения", Value = "3" });
            return group;
        }
        private readonly Web2.Data.AppDbContext _context;

        public AnalyzesModel(Web2.Data.AppDbContext context)
        {
            _context = context;
        }

        public IList<Models.Analyzes> analyzes { get;set; } = default!;

        public async Task OnGetAsync(int? group)
        {
			string email = User.Identity.Name.ToString();
			string role = "";
			var userP = await _context.user.FromSqlRaw($"SELECT * FROM \"AspNetUsers\" WHERE \"UserName\" = \'{email}\' ").ToListAsync();
			string id = userP[0].Id.ToString();

			if (User.IsInRole("Admin"))
			{
				role = "Admin";
			}
			else
			{
				role = "Doctor";
			}

			if (_context.analyzes != null)
            {
                switch (role)
                {
                    case "Admin":
						if (group == 0 || group == null)
							analyzes = await _context.analyzes.FromSqlRaw($"SELECT * FROM analyzes ORDER BY id_analysis").ToListAsync();
						else
							analyzes = await _context.analyzes.FromSqlRaw($"SELECT * FROM analyzes WHERE id_analysis IN(SELECT id_analysis FROM patient_analyzes WHERE id_patient IN(SELECT id_patient FROM patient_archive WHERE id_patient IN(SELECT id_patient FROM archive_group WHERE id_group={group}) ORDER BY id_patient)) ORDER BY id_analysis").ToListAsync();
						break;
                    case "Doctor":
						if (group == 0 || group == null)
							analyzes = await _context.analyzes.FromSqlRaw($"SELECT * FROM analyzes WHERE id_analysis IN(SELECT id_analysis FROM patient_analyzes WHERE id_patient IN(SELECT id_patient FROM patient_archive WHERE id_patient IN(SELECT id_patient FROM user_patients WHERE id_user=\'{id}\'))) ORDER BY id_analysis").ToListAsync();
						else
							analyzes = await _context.analyzes.FromSqlRaw($"SELECT * FROM analyzes WHERE id_analysis IN(SELECT id_analysis FROM patient_analyzes WHERE id_patient IN(SELECT id_patient FROM patient_archive WHERE id_patient IN(SELECT id_patient FROM user_patients WHERE id_user=\'{id}\') INTERSECT (SELECT id_patient FROM archive_group WHERE id_group={group}))) ORDER BY id_analysis").ToListAsync();
						break;
                } 
            }
        }
        public IActionResult OnPost(string G1)
        {
            int G = Convert.ToInt32(G1);
            string? url = Url.Page("Analyzes", new { group = G });

            return Redirect(url);
        }
        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var b = await _context.analyzes.FindAsync(id);
            if (b != null)
            {
                _context.analyzes.Remove(b);
                await _context.SaveChangesAsync();
            }
            return RedirectToPage("./Analyzes");
        }
    }
}

WebTest/Web2/Pages/Database/Analyzes/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web2.Models;

namespace Web2.Pages.Database.Analyzes
{
    public class CreateModel : PageModel
    {
        private readonly Data.AppDbContext _context;

        public CreateModel(Data.AppDbContext context)
        {
            _context = context;
        }
        public int idP = 1;
        public int varR = 0;
        [BindProperty]
        public Models.Analyzes Analyzes { get; set; }
        [BindProperty]
        public Patient_Analyzes P_A { get; set; }
        public IActionResult OnGet(int? id, int? var)
        {
            if (id != null)
            {
                idP = (int)id;
                varR = (int)var;
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(int idP, int varR)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.analyzes.Add(Analyzes);
            await _context.SaveChangesAsync();

            P_A.id_analysis = Analyzes.id_analysis;
            _context.patient_analyzes.Add(P_A);
            await _context.SaveChangesAsync();

            string str="";
            switch (varR) 
            {
                case 0:
                    str="./Analyzes";
                    break;
                case 1:
                    str=$"/Database/Patient_Analyzes?id={idP}";
                    break;
            }
            return Redirect(str);
        }

    }
}

WebTest/Web2/Pages/Database/Analyzes/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages.Database.Analyzes
{
    public class DetailsModel : PageModel
    {
        private readonly Web2.Data.AppDbContext _context;

        public DetailsModel(Web2.Data.AppDbContext context)
        {
            _context = context;
        }

      public Models.Analyzes Analyzes { get; set; } = default!;
      public Patient_Analyzes P_A { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.analyzes == null)
            {
                return NotFound();
            }

            var Analyzes = await _context.analyzes.FirstOrDefaultAsync(m => m.id_analysis == id);
            var P_A = await _context.patient_analyzes.FirstOrDefaultAsync(m => m.id_analysis == id);
            if (Analyzes == null)
            {
                return NotFound();
            }
            else 
            {
                this.Analyzes = Analyzes;
                this.P_A = P_A;
            }
            return Page();
        }
    }
}

WebTest/Web2/Pages/Database/Analyzes/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages.Database.Analyzes
{
    public class EditModel : PageModel
    {
        private readonly Web2.Data.AppDbContext _context;

        public EditModel(Web2.Data.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Analyzes Analyzes { get; set; }
        [BindProperty]
        public patient_archive Patient { get; set; }
        [BindProperty]
        public Patient_Analyzes P_A { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Analyzes = await _context.analyzes.FirstOrDefaultAsync(m => m.id_analysis == id);
            P_A = await _context.patient_analyzes.FirstOrDefaultAsync(m => m.id_analysis == id);

            if (Analyzes == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostEditAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var id_a = await _context.patient_analyzes.FromSqlRaw($"SELECT * FROM patient_analyzes WHERE id_analysis={Analyzes.id_analysis}").ToListAsync();
            var b = await _context.patient_analyzes.FindAsync(id_a[0].id_patient, Analyzes.id_analysis);
            if (b != null)
            {
                _context.patient_analyzes.Remove(b);
                await _context.SaveChangesAsync();
            }

            P_A.analyzes = Analyzes;
            _context.Attach(Analyzes).State = EntityState.Modified;
            _context.patient_analyzes.Add(P_A);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PatientExists(Analyzes.id_analysis))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Analyzes");
        }

        private bool PatientExists(int id)
        {
            return _context.analyzes.Any(e => e.id_analysis == id);
        }
    }
}

WebTest/Web2/Pages/Database/DB.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web2.Pages
{
    public class DBModel : PageModel
    {
        public void OnGet(){}
    }
}

WebTest/Web2/Pages/Database/Examinations/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages.Database.Examinations
{
    public class DetailsModel : PageModel
    {
        private readonly Web2.Data.AppDbContext _context;

        public DetailsModel(Web2.Data.AppDbContext context)
        {
            _context = context;
        }

      public Examination Examination { get; set; } = default!;
      public Patient_Examination P_E { get; set; } = default!;
        // получение определённых анализов
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.examination == null)
            {
                return NotFound();
            }

            var Examination = await _context.examination.FirstOrDefaultAsync(m => m.id_examination == id);
            var P_E = await _context.patient_examinations.FirstOrDefaultAsync(m => m.id_examination == id);
            if (Examination == null)
            {
                return NotFound();
            }
            else 
            {
                this.Examination = Examination;
                this.P_E = P_E;
            }
            return Page();
        }
    }
}

WebTest/Web2/Pages/Database/Patients/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages.Database.Patients
{
    public class DetailsModel : PageModel
    {
        private readonly Web2.Data.AppDbContext _context;

        public DetailsModel(Web2.Data.AppDbContext context)
        {
            _context = context;
        }
		public patient_archive patient_archive { get; set; } = default!;
	    public Archive_Group archive_group { get; set; } = default!;
        public patient_group patient_group { get; set; } = default!;
        // получение данных пациента
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.patient_archive == null)
            {
                return NotFound();
            }

            var patient_archive = await _context.patient_archive.FirstOrDefaultAsync(m => m.id_patient == id);
			var archive_group = await _context.archive_group.FirstOrDefaultAsync(m => m.id_patient == id);
            var patient_group = await _context.patient_groups.FirstOrDefaultAsync(m => m.id_group == archive_group.id_group);
            if (patient_archive == null)
            {
                return NotFound();
            }
            else 
            {
                this.patient_archive = patient_archive;
				this.patient_group = patient_group;
			}
            return Page();
        }
    }
}

WebTest/Web2/Pages/Database/Patients/Patients.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages.Database.Patients
{
    public class DatabaseModel : PageModel
    {
        // выбор группы
		public List<SelectListItem>? GetGroup()
        {
            List<SelectListItem> group = new List<SelectListItem>();
            group.Add(new SelectListItem() { Text = "Контрольная группа", Value = "1" });
            group.Add(new SelectListItem() { Text = "Основная группа", Value = "2" });
            group.Add(new SelectListItem() { Text = "Группа сравнения", Value = "3" });
            return group;
        }
        private readonly Web2.Data.AppDbContext _context;

        public DatabaseModel(Web2.Data.AppDbContext context)
        {
            _context = context;
        }

        public IList<patient_archive> patient_archive { get;set; } = default!;
		public IList<User> user { get; set; } = default!;
        // получение архива пациентов
        public async Task OnGetAsync(int? group)
        {
			string email = User.Identity.Name.ToString();
            string role = "";
			var userP = await _context.user.FromSqlRaw($"SELECT * FROM \"AspNetUsers\" WHERE \"UserName\" = \'{email}\' ").ToListAsync();
            string id = userP[0].Id.ToString();

            if (User.IsInRole("Admin"))
            {
                role = "Admin";
            }
            else
            {
                role = "Doctor";
            }

            if (_context.patient_archive != null)
            {
                switch (role)
                {
                    case "Admin":
						if (group == 0 || group == null)
							patient_archive = await _context.patient_archive.FromSqlRaw($"SELECT * FROM patient_archive ORDER BY id_patient").ToListAsync();
						else
							patient_archive = await _context.patient_archive.FromSqlRaw($"SELECT * FROM patient_archive WHERE id_patient IN(SELECT id_patient FROM archive_group WHERE id_group={group}) ORDER BY id_patient").ToListAsync();
						break;
                    case "Doctor":
						if (group == 0 || group == null)
							patient_archive = await _context.patient_archive.FromSqlRaw($"SELECT * FROM patient_archive WHERE id_patient IN(SELECT id_patient FROM user_patients WHERE id_user=\'{id}\') ORDER BY id_patient").ToListAsync();
						else
							patient_archive = await _context.patient_archive.FromSqlRaw($"SELECT * FROM patient_archive WHERE id_patient IN( (SELECT id_patient FROM user_patients WHERE id_user=\'{id}\') INTERSECT (SELECT id_patient FROM archive_group WHERE id_group={group})) ORDER BY id_patient").ToListAsync();
						break;
                }
            }
        }
        // вывод пациентов определённой группы
        public IActionResult OnPost(string G1)
        {
            int G = Convert.ToInt32(G1);
            string? url = Url.Page("Database", new { group = G });

            return Redirect(url);
        }
        // удаление пациента из БД
        public async Task<IActionResult> OnPostDeleteAsync(int id)
		{
			var b = await _context.patient_archive.FindAsync(id);

            var A = await _context.analyzes.FromSqlRaw($"SELECT * FROM analyzes WHERE id_analysis IN (SELECT id_analysis FROM patient_analyzes WHERE id_patient={id})").ToListAsync();
			var C = await _context.examination.FromSqlRaw($"SELECT * FROM examination WHERE id_examination IN (SELECT id_examination FROM patient_examinations WHERE id_patient={id})").ToListAsync();

			if (b != null)
			{
				_context.patient_archive.Remove(b);  

				if (A != null)
				{
                    for (int i = 0; i < A.Count; i++)
                    {
                        _context.analyzes.Remove(A[i]);
                    }
				}
				if (C != null)
				{
					for (int i = 0; i < C.Count; i++)
					{
						_context.examination.Remove(C[i]);
					}
				}
				await _context.SaveChangesAsync();

            }
            string? url = Url.Page("Database", new { group = 0 });
            return Redirect(url);
        }
    }
}

WebTest/Web2/Pages/Database/Examinations/Create.cshtml
@page
@model Web2.Pages.Database.Examinations.CreateModel
@{
	ViewData["Title"] = "Create";
}

<h1>Добавление</h1>

<h4>Диспансеризация</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <input asp-for="idP" name="idP" style="display:none" />
            <input asp-for="varR" name="varR" style="display:none" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label>Номер пациента</label>
                <input asp-for="P_E.id_patient" class="form-control" value="@Model.idP" min="1" />
                <span asp-validation-for="P_E.id_patient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Дата прохождения</label>
                <input asp-for="Examination.date" class="form-control" type="date" id="day" min="1925-01-01" max=""/>
                <span asp-validation-for="Examination.date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Время удержания позы</label>
                <input asp-for="Examination.posture_holding_time" class="form-control" min="0" />
                <span asp-validation-for="Examination.posture_holding_time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Величина кифоза в градусах в грудном отделе позвоночника</label>
                <input asp-for="Examination.the_amount_of_kyphosis_in_degress" class="form-control" min="0" max="120"/>
                <span asp-validation-for="Examination.the_amount_of_kyphosis_in_degress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Изменение контуров замыкательных пластинок</label>
                <input asp-for="Examination.changing_the_contours_of_the_end_plates" class="checkbox" />
                <span asp-validation-for="Examination.changing_the_contours_of_the_end_plates" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Клиновидная форма тел позвонков</label>
                <input asp-for="Examination.wedgeshaped_vertebral_bodies" class="checkbox" />
                <span asp-validation-for="Examination.wedgeshaped_vertebral_bodies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Грыжи Шморля</label>
                <input asp-for="Examination.schmorl_hernia" class="checkbox" />
                <span asp-validation-for="Examination.schmorl_hernia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Остеопороз тел позвонков</label>
                <input asp-for="Examination.osteoporosis_of_the_vertebrae" class="checkbox" />
                <span asp-validation-for="Examination.osteoporosis_of_the_vertebrae" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Уменьшение высоты межпозвоночного диска</label>
                <input asp-for="Examination.decrease_in_the_height_of_the_intervertebral_disc" class="checkbox" />
                <span asp-validation-for="Examination.decrease_in_the_height_of_the_intervertebral_disc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Изменение контуров апофизов</label>
                <input asp-for="Examination.change_in_the_contours_of_the_apophyses" class="checkbox" />
                <span asp-validation-for="Examination.change_in_the_contours_of_the_apophyses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Признаки остеохондроза</label>
                <input asp-for="Examination.signs_of_osteochondrosis" class="checkbox" />
                <span asp-validation-for="Examination.signs_of_osteochondrosis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Стабилографические изменения</label>
                <input asp-for="Examination.stabilographic_changes" class="checkbox" />
                <span asp-validation-for="Examination.stabilographic_changes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>ЭНМГ</label>
                <input asp-for="Examination.enmg" class="checkbox" />
                <span asp-validation-for="Examination.enmg" class="text-danger"></span>
            </div>
            <p>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
            </p>
        </form>
    </div>
</div>

<div>
    @if (Model.varR == 0)
    {
        <a asp-page="./Examinations">Назад</a>
    }
    else
    {
        <a href="/Database/Patient_Examinations?id=@Model.idP">Назад</a>
    }
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>

        const options = {
            year: 'numeric',
            month: 'numeric',
            day: 'numeric',
        }

        const date = new Date()
        const tomorrow = date.toLocaleString("ru", options).split('.').reverse().join('-')
        document.getElementById("day").setAttribute("max", tomorrow)
    </script>
}

WebTest/Web2/Pages/Database/Examinations/Details.cshtml
@page
@model Web2.Pages.Database.Examinations.DetailsModel

@{
    Layout = null;
}

@{
    ViewData["Title"] = "Details";
}

<body>

<h1>Подробности</h1>

<div>
    <h4>Диспансеризация</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-9">
            Номер пациента
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.P_E.id_patient)
        </dd>
        <dt class="col-sm-9">
            Дата прохождения
            </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.date)
        </dd>
        <dt class="col-sm-9">
            Время удержания позы
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.posture_holding_time)
        </dd>
        <dt class="col-sm-9">
            Величина кифоза в градусах в грудном отделе позвоночника
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.the_amount_of_kyphosis_in_degress)
        </dd>
        <dt class="col-sm-9">
            Изменение контуров замыкательных пластинок
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.changing_the_contours_of_the_end_plates)
        </dd>
        <dt class="col-sm-9">
            Клиновидная форма тел позвонков
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.wedgeshaped_vertebral_bodies)
        </dd>
        <dt class="col-sm-9">
            Грыжи Шморля
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.schmorl_hernia)
        </dd>
        <dt class="col-sm-9">
            Остеопороз тел позвонков
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.osteoporosis_of_the_vertebrae)
        </dd>
        <dt class="col-sm-9">
            Уменьшение высоты межпозвоночного диска
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.decrease_in_the_height_of_the_intervertebral_disc)
        </dd>
        <dt class="col-sm-9">
            Изменение контуров апофизов
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.change_in_the_contours_of_the_apophyses)
        </dd>
        <dt class="col-sm-9">
            Признаки остеохондроза
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.signs_of_osteochondrosis)
        </dd>
        <dt class="col-sm-9">
            Стабилографические изменения
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.stabilographic_changes)
        </dd>
        <dt class="col-sm-9">
            ЭНМГ
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Examination.enmg)
        </dd>
    </dl>
</div>

</body>

WebTest/Web2/Pages/Database/Examinations/Edit.cshtml
@page
@model Web2.Pages.Database.Examinations.EditModel

@{
    Layout = null;
}

@{
	ViewData["Title"] = "Edit";
}

<body>

<h1>Редактирование</h1>

<h4>Диспансеризация</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-page-handler="edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Examination.id_examination" />
            <div class="form-group">
                <label>Номер пациента</label>
                <input asp-for="P_E.id_patient" class="form-control" min="1" />
                <span asp-validation-for="P_E.id_patient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Дата прохождения</label>
                <input type="date" value="@Model.Examination.date.ToString("yyyy-MM-dd")" asp-for="Examination.date" class="form-control" id="day" min="1925-01-01" max="" />
                <span asp-validation-for="Examination.date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Время удержания позы</label>
                <input asp-for="Examination.posture_holding_time" class="form-control" min="0" />
                <span asp-validation-for="Examination.posture_holding_time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Величина кифоза в градусах в грудном отделе позвоночника</label>
                <input asp-for="Examination.the_amount_of_kyphosis_in_degress" class="form-control" min="0" />
                <span asp-validation-for="Examination.the_amount_of_kyphosis_in_degress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Изменение контуров замыкательных пластинок</label>
                <input asp-for="Examination.changing_the_contours_of_the_end_plates" class="checkbox" />
                <span asp-validation-for="Examination.changing_the_contours_of_the_end_plates" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Клиновидная форма тел позвонков</label>
                <input asp-for="Examination.wedgeshaped_vertebral_bodies" class="checkbox" />
                <span asp-validation-for="Examination.wedgeshaped_vertebral_bodies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Грыжи Шморля</label>
                <input asp-for="Examination.schmorl_hernia" class="checkbox" />
                <span asp-validation-for="Examination.schmorl_hernia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Остеопороз тел позвонков</label>
                <input asp-for="Examination.osteoporosis_of_the_vertebrae" class="checkbox" />
                <span asp-validation-for="Examination.osteoporosis_of_the_vertebrae" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Уменьшение высоты межпозвоночного диска</label>
                <input asp-for="Examination.decrease_in_the_height_of_the_intervertebral_disc" class="checkbox" />
                <span asp-validation-for="Examination.decrease_in_the_height_of_the_intervertebral_disc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Изменение контуров апофизов</label>
                <input asp-for="Examination.change_in_the_contours_of_the_apophyses" class="checkbox" />
                <span asp-validation-for="Examination.change_in_the_contours_of_the_apophyses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Признаки остеохондроза</label>
                <input asp-for="Examination.signs_of_osteochondrosis" class="checkbox" />
                <span asp-validation-for="Examination.signs_of_osteochondrosis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Стабилографические изменения</label>
                <input asp-for="Examination.stabilographic_changes" class="checkbox" />
                <span asp-validation-for="Examination.stabilographic_changes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>ЭНМГ</label>
                <input asp-for="Examination.enmg" class="checkbox" />
                <span asp-validation-for="Examination.enmg" class="text-danger"></span>
            </div>
            <p>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
            </p>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

</body>